/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Yrityspeli_package;
import static Yrityspeli_package.j2a_Uusi_peli.jd;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.UnsupportedLookAndFeelException;
/**
 * @author Niko L. & Timo K. Dat16A
 * Ota yhteyttä, jos tarvitset lisätietoja
 * brandis.palaute@gmail.com
 * Copyright ©Brandis, All rights reserved 
 */
public class j1_Aloitus extends javax.swing.JFrame {//Ensimmäin ikkuna joka tulee näytölle
     //Frame importti
    final j1_Aloitus ji;
    //Alustus cordinaatille, joka liittyy framen "draggaamiseen", siirtelyyn
    private static Point compCoords;			
/**
 * Creates new form j1_Aloitus
     * @param Aloitus
     * @throws java.lang.ClassNotFoundException
     * @throws java.io.IOException
 */
public j1_Aloitus(j1_Aloitus Aloitus) throws ClassNotFoundException, IOException, SQLException {
    System.out.println("->Avataan j1_Aloitus.java");
    //Poistetaan framen koristelut
    this.setUndecorated(true);
    initComponents();
    //Alustetaan mitta dim, jonka arvot käydään käyttäjän näytön mitoista.
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    //Siirretään frame keskelle näyttöä
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    //Muutetaan JPanel1:sen & JPanel2:sen väriä siniseksi
    jPanel2.setBackground(new Color(76, 181, 245));
    jPanel1.setBackground(new Color(76, 181, 245));
    //Muutetaan jButtonejen väriä valkeaksi
    UusiBtn.setBackground(Color.WHITE);
    LataaBtn.setBackground(Color.WHITE);
    PoistuBtn.setBackground(Color.WHITE);
    AboutBtn.setBackground(Color.WHITE);
    //Tallenetaan tieto ji-nimisen konstruktoriin tämän framen konstruktorista
    this.ji = this;
    //Metodi framen siirtelyyn
    Palkki();
    TarkistaTallennukset();
    
}



    j1_Aloitus() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException, SQLException {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
			break;
			}
		}
         System.out.println("->Avataan j1_Aloitus.java");
    //Poistetaan framen koristelut
    this.setUndecorated(true);
    initComponents();
    //Alustetaan mitta dim, jonka arvot käydään käyttäjän näytön mitoista.
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    //Siirretään frame keskelle näyttöä
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    //Muutetaan JPanel1:sen & JPanel2:sen väriä siniseksi
    jPanel2.setBackground(new Color(76, 181, 245));
    jPanel1.setBackground(new Color(76, 181, 245));
    //Muutetaan jButtonejen väriä valkeaksi
    UusiBtn.setBackground(Color.WHITE);
    LataaBtn.setBackground(Color.WHITE);
    PoistuBtn.setBackground(Color.WHITE);
    AboutBtn.setBackground(Color.WHITE);
    //Tallenetaan tieto ji-nimisen konstruktoriin tämän framen konstruktorista
    this.ji = this;
    //Metodi framen siirtelyyn
    Palkki();
    TarkistaTallennukset();
    }

/**
* This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UusiBtn = new javax.swing.JButton();
        LataaBtn = new javax.swing.JButton();
        PoistuBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AboutBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Päävalikko");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(12, 143, 222));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BRANDIS v1.0 ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Yrityspelisimulaattori");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        UusiBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UusiBtn.setText("Uusi Peli");
        UusiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UusiBtnActionPerformed(evt);
            }
        });

        LataaBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LataaBtn.setText("Lataa peli");
        LataaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LataaBtnActionPerformed(evt);
            }
        });

        PoistuBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PoistuBtn.setText("Poistu");
        PoistuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoistuBtnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("v0.01");

        AboutBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AboutBtn.setText("Tekijät");
        AboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("(Dev Tools)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PoistuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LataaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AboutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UusiBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UusiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LataaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PoistuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void UusiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UusiBtnActionPerformed
    try {
        System.out.println(">Uusi peli valittu");
        //Avaa jFramen "j2a_Uusi_Peli.java" ja sulkee jFramen "j1_Aloitus.java" komennola .dispose()
        System.out.println("j1_Aloitus.java -> dispose");
        //Luodaan uusi frame konstruktorilla, joka vaatii "this" parametrin.
        j2a_Uusi_peli UusiPeli = new j2a_Uusi_peli(this);
        //Keskitetään J2a_Uusi_peli
        UusiPeli.setLocationRelativeTo(null);
        //Laitetaan j2a_Uusi_peli näkyviin
        UusiPeli.setVisible(true);
        //Alustetaan tietokannat
        DELETE();
        //Suljetaan tämä frame
        this.dispose();
        
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(j1_Aloitus.class.getName()).log(Level.SEVERE, null, ex);
    }
										
										
     }//GEN-LAST:event_UusiBtnActionPerformed

     
     private void DELETE() throws ClassNotFoundException, SQLException{
        //Tyhjennetään PTuote ja PMyyja JBDC kautta.
         jd.putData("delete from PTuote");
         jd.putData("delete from PMyyja");
     }
     private void LataaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LataaBtnActionPerformed
    try {
        //Avaa jFramen "j2b_lataa_peli.java"
        DELETE();
        j2b_lataa_peli frame2 = new j2b_lataa_peli();
        frame2.pack();
        frame2.setVisible(true);
        frame2.setLocationRelativeTo(null);
        this.dispose();
    } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        Logger.getLogger(j1_Aloitus.class.getName()).log(Level.SEVERE, null, ex);
    }
     }//GEN-LAST:event_LataaBtnActionPerformed

    private void PoistuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoistuBtnActionPerformed
        //Laitetaan frameen "dispatch eventti", joka sulkee framen.
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_PoistuBtnActionPerformed

    private void AboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBtnActionPerformed
        
        try {
            Tekijat t = new Tekijat();
            t.setVisible(true);
            t.setLocationRelativeTo(null);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(j1_Aloitus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AboutBtnActionPerformed

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	try {
            SQLTaulut dev = new SQLTaulut();
            dev.setVisible(true);
	} catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(j1_Aloitus.class.getName()).log(Level.SEVERE, null, ex);
	}
										
     }//GEN-LAST:event_jButton1ActionPerformed
/**
* @param args the command line arguments
 */
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
 */
try {
	for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
		javax.swing.UIManager.setLookAndFeel(info.getClassName());
		break;
            }
	}
} catch (ClassNotFoundException ex) {
    java.util.logging.Logger.getLogger(j1_Aloitus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
    java.util.logging.Logger.getLogger(j1_Aloitus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
    java.util.logging.Logger.getLogger(j1_Aloitus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(j1_Aloitus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>
 
/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
    try {
        new j1_Aloitus().setVisible(false);
        j1_Aloitus Aloitus = new j1_Aloitus();
        Aloitus = new j1_Aloitus(Aloitus);
        Aloitus.setVisible(true);
    } catch (ClassNotFoundException | IOException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | SQLException ex) {
        Logger.getLogger(j1_Aloitus.class.getName()).log(Level.SEVERE, null, ex);
    }
   
}
});
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutBtn;
    private javax.swing.JButton LataaBtn;
    private javax.swing.JButton PoistuBtn;
    private javax.swing.JButton UusiBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

private void Palkki() { 
    
    this.getContentPane().setBackground(new Color(76, 181, 245));
        //Lisätään jPanel1:selle mouse listener
         jPanel1.addMouseListener(new MouseListener() {
            //Eventti joka tapahtuu silloin, kun hiiren napista päästetään irti
            @Override
            public void mouseReleased(MouseEvent e) {
                //Tyhjennetään kordinaatit
                compCoords = null;
                //Palautetaan reunuksen väri
                jPanel2.setBorder(BorderFactory.createLineBorder(new Color(12, 143, 222)));
            }
            
            //Eventti kun hiirtä painetaan
            @Override
            public void mousePressed(MouseEvent e) {
                //Kordinaatit = e eventin kohta
                compCoords = e.getPoint();
                //Muutetaan reunuksen väri oransiksi
                jPanel2.setBorder(BorderFactory.createLineBorder(Color.ORANGE));
            }

           
            @Override
            public void mouseExited(MouseEvent e) {
            }

            
            @Override
            public void mouseEntered(MouseEvent e) {
            }

            
            @Override
            public void mouseClicked(MouseEvent e) {
            }
        });
         //Listätään JPanel1:lle liike listeneri
       jPanel1.addMouseMotionListener(new MouseMotionListener() {
            @Override
            public void mouseMoved(MouseEvent e) {
            }

            @Override
            //Eventti kun hiirellä raahataan
            public void mouseDragged(MouseEvent e) {
                //Point = e:n sijainti näytöllä
                Point currCoords = e.getLocationOnScreen();
                //Pävitetään frame currCoordsin sijaintiin
                ji.setLocation(currCoords.x - compCoords.x, currCoords.y - compCoords.y);
                
            }
        });
       
    }

    private void TarkistaTallennukset() throws ClassNotFoundException, SQLException {
        JDBC jd  = new JDBC();
        try (Connection con = jd.getConnection()) {
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select * from pelaajat");
            if(rs.next()){
                LataaBtn.setEnabled(true);
                System.out.println("Tallennuksia on");
            }
            else{
                LataaBtn.setEnabled(false);
                System.out.println("Tallennuksia ei ole");
            }
        }
        
        
    }



}

