/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Yrityspeli_package;

import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Niko L. & Timo K.
 * Ota yhteyttä jos tarvitset lisätietoja
 * brandis.palaute@gmail.com
 * Copyright ©Brandis, All rights reserved
 */
public class j2b_lataa_peli extends javax.swing.JFrame {
	j3_Paaikkuna ji;
        public j2b_lataa_peli jin;
        JDBC jd = new JDBC();
        JPanel main;
        Point compCoords;
                                        
    /**
     * Creates new form j2b_lataa_peli
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public j2b_lataa_peli() throws ClassNotFoundException, SQLException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        //Muutetaan teema Nimbuksesta Metalliksi
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
			break;
			}
           
              
               
                
		}
              //Värjätään jFramen "content pane" valkoiseksi
              this.getContentPane().setBackground(Color.WHITE);
                this.getContentPane().setBackground(Color.WHITE);
        main = (JPanel)this.getContentPane();
        main.setBorder(BorderFactory.createLineBorder(new Color(12, 143, 222)));
                //Värjätään napit UIManagerilla
                UIManager.put("Button.background", new Color(76, 181, 245));
                UIManager.put("Button.foreground", Color.WHITE);
        initComponents();
         this.jin = this;
          Palkki();
	      LataaPelit();
              //Värjätään tablen rivit
                PELITTABLE.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
{
    
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
    {
        final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        c.setBackground(row % 2 == 0 ?  Color.WHITE: new Color(157, 223, 255));
        if(isSelected) {setBackground(new Color(168, 226, 255));}
        if(!isSelected) {setBackground(Color.WHITE);}
        return c;
        
    }
    
});
                //Värjätään tablen otsikot
                DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
                headerRenderer.setBackground(new Color(76, 181, 245));
                for (int j = 0; j < PELITTABLE.getModel().getColumnCount(); j++) {
        PELITTABLE.getColumnModel().getColumn(j).setHeaderRenderer(headerRenderer);
}
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PELITTABLE = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        VEDA = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PELITTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Yrityksen nimi", "Slogan", "Kuukausi", "Omaisuus", "Luomispäivämäärä"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PELITTABLE.getTableHeader().setResizingAllowed(false);
        PELITTABLE.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(PELITTABLE);

        jButton1.setText("Lataa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Poista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 102, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CLEANSE DEV");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Peruuta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        VEDA.setBackground(new java.awt.Color(76, 181, 245));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tallennetut pelit");

        javax.swing.GroupLayout VEDALayout = new javax.swing.GroupLayout(VEDA);
        VEDA.setLayout(VEDALayout);
        VEDALayout.setHorizontalGroup(
            VEDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VEDALayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VEDALayout.setVerticalGroup(
            VEDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VEDALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VEDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VEDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	try {
                //Haetaan arvot peliin
		int row = PELITTABLE.getSelectedRow();//Hankkii valitun rivin myyjä tablesta
		Object KASSA = PELITTABLE.getValueAt(row, 2);
		Object YRNIMI = PELITTABLE.getValueAt(row, 0);
		Object Slogan = PELITTABLE.getValueAt(row, 1);
                Connection con = jd.getConnection();//Hakee yhteyden SQL-kantaan
                System.out.println("Con Lataapeli");
                Statement stm = con.createStatement();
                double brandos = 0.0;
                ResultSet rs = stm.executeQuery("Select *from tallennus where pnimi='"+YRNIMI.toString()+"'");
                while(rs.next()){
                    brandos = rs.getDouble("brandi");
                    System.out.println("Ladattu brandi on "+brandos);
                }
                //Tuodaan arvot ladattuun peliin 
		ji = new j3_Paaikkuna();     
		ji = new j3_Paaikkuna(YRNIMI.toString(), Slogan.toString(), Double.valueOf(KASSA.toString()), false);
                jd.putData("insert into PMyyja(nimi,palkka) values('Omistaja',0)");
                ji.BRANDIPALKKI.setValue(Integer.valueOf(String.valueOf(Math.round(brandos))));
		ji.setVisible(true);
                ji.setLocationRelativeTo(null);
                ji.haenakki();
                ji.paivita();
                ji.paivitaMyyja();
		this.dispose();
	} catch (SQLException | ClassNotFoundException | LineUnavailableException | UnsupportedAudioFileException | IOException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
		Logger.getLogger(j2b_lataa_peli.class.getName()).log(Level.SEVERE, null, ex);
	}
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
	try {
		//Tyhjennetään kaikki taulut
		jd.putData("delete from tallennus");
		jd.putData("delete from pelaajat");
                jd.putData("delete from PTuote");
                jd.putData("delete from PMyyja");
                jd.putData("delete from TMtilastot");
		jd.putData("delete from Tilastot");
		DefaultTableModel model = (DefaultTableModel) PELITTABLE.getModel();							
		int rowCount = model.getRowCount();
        
        for (int i = rowCount - 1; i >= 0; i--) {
        }
															
} catch (ClassNotFoundException | SQLException ex) {
	Logger.getLogger(j2b_lataa_peli.class.getName()).log(Level.SEVERE, null, ex);
										}
     }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          try {
              //Peruuta napin syntaksi
               j1_Aloitus a = new j1_Aloitus();
               a.setVisible(true);
               this.dispose();       
          } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | SQLException ex) {
             Logger.getLogger(j2b_lataa_peli.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
           //Rivinpoisto PELITTABLEsta
            Connection con = jd.getConnection();//Hakee yhteyden SQL-kantaan
            System.out.println("Con Lataapeli");
            Statement stm = con.createStatement();
            int row = PELITTABLE.getSelectedRow();
            if(row == -1){
                JOptionPane.showMessageDialog(null, "Valitse ensin rivi, jonka haluat poistaa!");
            }else{
                jd.putData("Delete from pelaajat where nimi ='"+PELITTABLE.getValueAt(row,0)+"'");
                jd.putData("Delete from Tilastot where yrnim ='"+PELITTABLE.getValueAt(row,0)+"'");
                jd.putData("Delete from TMTilastot where yrnim ='"+PELITTABLE.getValueAt(row,0)+"'");
                jd.putData("Delete from Tallennus where pnimi ='"+PELITTABLE.getValueAt(row,0)+"'");
                DefaultTableModel model = (DefaultTableModel) PELITTABLE.getModel();
                model.removeRow(row);
                
            }
       } catch (ClassNotFoundException | SQLException ex) {
         Logger.getLogger(j2b_lataa_peli.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j2b_lataa_peli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j2b_lataa_peli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j2b_lataa_peli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j2b_lataa_peli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
		try {
		new j2b_lataa_peli().setVisible(true);
		} catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
		Logger.getLogger(j2b_lataa_peli.class.getName()).log(Level.SEVERE, null, ex);
		}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PELITTABLE;
    private javax.swing.JPanel VEDA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void LataaPelit() throws ClassNotFoundException, SQLException {
        //Lataapelit syntaksi. Käydään arvot SQL-taulusta, sisällytetän ne ArrayListiin ja ladataan ne PELITTABLEen.
	ArrayList<Peli>p = new ArrayList();
	Peli p1 = new Peli("?", "?", 0, "?", "?");
						
        Connection con = jd.getConnection();
	String SA = "select * from ";			
        Statement stm = con.createStatement();
        ResultSet rs = stm.executeQuery(SA+"tallennus");
	Object t[] = new Object[5];		

StringBuilder sp = new StringBuilder();
        while(rs.next()){
	sp.delete(0, sp.length());
	sp.append(rs.getInt("kk"));
        sp.append(".");  
        sp.append(rs.getInt("v"));
				 				
	p1 = new Peli(rs.getString("pnimi"), rs.getString("pslogan"), rs.getDouble("pkassa"), String.valueOf(sp), rs.getString("lpvm"));		
												
	p.add(p1);
	} 
	DefaultTableModel m = (DefaultTableModel)PELITTABLE.getModel();
	for (int i = 0; i < p.size(); i++) {
           
         double domaisuus = p.get(i).getOmaisuus();
         String soimaisuus = String.format("%.2f", domaisuus);
         soimaisuus = soimaisuus.replaceAll(",", ".");
            
	t[0]=p.get(i).getNimi();
        t[1]=p.get(i).getSlogan();	
	t[2]=p.get(i).getAika();
	t[3]=soimaisuus+"€";
	t[4]=p.get(i).getLpvm();
	
	m.addRow(t);
	}
	con.close();
        
					
}
private void Palkki() {
        //Custom otiskkobarin syntaksi. Lisätietoja toteuteksesta: https://www.youtube.com/watch?v=fT8gl6R2xmc
        
        VEDA.addMouseListener(new MouseListener() {
            @Override
            public void mouseReleased(MouseEvent e) {
                compCoords = null;
                main.setBorder(BorderFactory.createLineBorder(new Color(12, 143, 222)));
                VEDA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }

            @Override
            public void mousePressed(MouseEvent e) {
                compCoords = e.getPoint();
                main.setBorder(BorderFactory.createLineBorder(Color.ORANGE));
                 VEDA.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseClicked(MouseEvent e) {
            }
        });
       VEDA.addMouseMotionListener(new MouseMotionListener() {
            @Override
            public void mouseMoved(MouseEvent e) {
            }

            @Override
            public void mouseDragged(MouseEvent e) {
                Point currCoords = e.getLocationOnScreen();
               
                jin.setLocation(currCoords.x - compCoords.x, currCoords.y - compCoords.y);
                //ImageIcon PlusIcon = new ImageIcon(getClass().getResource("/Img/Buttons/menu_button.png"));
                //MENU.setIcon(PlusIcon);
                
															
															
                
            }
        });
    }

}