/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Yrityspeli_package;

//import static Yrityspeli_package.j4c_Ostot.con;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 * @author Niko L. & Timo K. Dat16A
 * Ota yhteyttä jos tarvitset lisätietoja
 * brandis.palaute@gmail.com
 * Copyright ©Brandis, All rights reserved
 */
public class j4c_Hyvantekevaisyys extends javax.swing.JFrame {
    public String YRNIM;
    public j4c_Hyvantekevaisyys ji;
    public Point compCoords;
    JPanel main;
    /**
     * Creates new form j4d_Hyvantekevaisyys
     */
    public j4c_Hyvantekevaisyys() {
        initComponents();
    }
    j4c_Hyvantekevaisyys(String YRNIM){
        
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        main = (JPanel)this.getContentPane();
        main.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        this.YRNIM = YRNIM;
        this.ji = this;
        //Haetaan tämänhetkinen hnyväntekeväisyys
        haeHT();
        Palkki();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VAIHDABTN = new javax.swing.JButton();
        OUTPUTTEKEVAISYYS = new javax.swing.JLabel();
        POISTUBTN = new javax.swing.JButton();
        HYVANTEKEVAISYYSCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        VEDA = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        VAIHDABTN.setText("Vaihda");
        VAIHDABTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAIHDABTNActionPerformed(evt);
            }
        });

        OUTPUTTEKEVAISYYS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        POISTUBTN.setText("Poistu");
        POISTUBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POISTUBTNActionPerformed(evt);
            }
        });

        HYVANTEKEVAISYYSCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "500.00", "1500.00", "2000.00", "2500.00" }));

        jLabel2.setText("€");

        VEDA.setBackground(new java.awt.Color(76, 181, 245));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hyväntekeväisyys");

        javax.swing.GroupLayout VEDALayout = new javax.swing.GroupLayout(VEDA);
        VEDA.setLayout(VEDALayout);
        VEDALayout.setHorizontalGroup(
            VEDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VEDALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VEDALayout.setVerticalGroup(
            VEDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jLabel1.setText("Tämänhetkinen hyväntekeväisyys");

        jLabel4.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VEDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HYVANTEKEVAISYYSCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OUTPUTTEKEVAISYYS, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VAIHDABTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(POISTUBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VEDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OUTPUTTEKEVAISYYS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HYVANTEKEVAISYYSCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VAIHDABTN)
                                .addComponent(POISTUBTN)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VAIHDABTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAIHDABTNActionPerformed
        try {
            //Syntäksi hyväntekeväisyyden vaihtoon. Huom! Hyväntekeväisyys itsessään on vielä pahasti
            //vaiheessa oleva toiminto. Tällä hetkellä se lisää myyntiä liian rajusti. Kokeellinen!
            OUTPUTTEKEVAISYYS.setText(HYVANTEKEVAISYYSCB.getSelectedItem().toString());
            JDBC JD = new JDBC();
            Connection con = JD.getConnection();
            Statement stm = con.createStatement();
            double HT = Double.parseDouble(OUTPUTTEKEVAISYYS.getText());
            ResultSet pelaaja = stm.executeQuery("SELECT * FROM pelaajat");
            while(pelaaja.next()){
                if(pelaaja.getString("nimi").equals(YRNIM)){
                    stm.executeUpdate("UPDATE pelaajat set hyvantekevaisyys = " + HT +" WHERE nimi = '" + YRNIM + "'");
                }
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(j4c_Hyvantekevaisyys.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(j4c_Hyvantekevaisyys.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_VAIHDABTNActionPerformed

    private void POISTUBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POISTUBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_POISTUBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j4c_Hyvantekevaisyys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j4c_Hyvantekevaisyys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j4c_Hyvantekevaisyys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j4c_Hyvantekevaisyys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new j4c_Hyvantekevaisyys().setVisible(true);
        });
    }
    
    private void haeHT(){
        try {
            //Syntaksi tämänhetkisen hyväntekeväisyyden hakuun.
            JDBC JD = new JDBC();
            
            Connection con = JD.getConnection();
            Statement stm = con.createStatement();
            ResultSet pelaaja = stm.executeQuery("SELECT * FROM pelaajat");
            while(pelaaja.next()){
                if(pelaaja.getString("nimi").equals(YRNIM)){
                    OUTPUTTEKEVAISYYS.setText(String.valueOf(pelaaja.getDouble("hyvantekevaisyys")));
                }
            }
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(j4c_Hyvantekevaisyys.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(j4c_Hyvantekevaisyys.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
     private void Palkki() {
        
        VEDA.addMouseListener(new MouseListener() {
            @Override
            public void mouseReleased(MouseEvent e) {
                compCoords = null;
                main.setBorder(BorderFactory.createLineBorder(new Color(12, 143, 222)));
                VEDA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }

            @Override
            public void mousePressed(MouseEvent e) {
                compCoords = e.getPoint();
                main.setBorder(BorderFactory.createLineBorder(Color.ORANGE));
                 VEDA.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseClicked(MouseEvent e) {
            }
        });
       VEDA.addMouseMotionListener(new MouseMotionListener() {
            @Override
            public void mouseMoved(MouseEvent e) {
            }

            @Override
            public void mouseDragged(MouseEvent e) {
                Point currCoords = e.getLocationOnScreen();
               
                ji.setLocation(currCoords.x - compCoords.x, currCoords.y - compCoords.y);
                //ImageIcon PlusIcon = new ImageIcon(getClass().getResource("/Img/Buttons/menu_button.png"));
                //MENU.setIcon(PlusIcon);
                
															
															
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HYVANTEKEVAISYYSCB;
    private javax.swing.JLabel OUTPUTTEKEVAISYYS;
    private javax.swing.JButton POISTUBTN;
    private javax.swing.JButton VAIHDABTN;
    private javax.swing.JPanel VEDA;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
