/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Yrityspeli_package;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Niko
 */
public class SQLTaulut extends javax.swing.JFrame {
                JDBC JD = new JDBC();
					/**
					 * Creates new form SQLTaulut
					 */
					public SQLTaulut() throws SQLException, ClassNotFoundException {
										initComponents();
										HaeTiedot();
					}

					/**
					 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
					 */
					@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jScrollPane2 = new javax.swing.JScrollPane();
          TilastotTable = new javax.swing.JTable();
          jLabel1 = new javax.swing.JLabel();
          jButton1 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          TilastotTable.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18", "Title 19", "Title 20", "Title 21", "Title 22"
               }
          ));
          jScrollPane2.setViewportView(TilastotTable);

          jLabel1.setText("Tilastot");

          jButton1.setText("Päivitä");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1430, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(jButton1)))
                    .addGap(0, 52, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(jButton1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(440, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
										try {
															HaeTiedot();
										} catch (SQLException ex) {
															Logger.getLogger(SQLTaulut.class.getName()).log(Level.SEVERE, null, ex);
										} catch (ClassNotFoundException ex) {
															Logger.getLogger(SQLTaulut.class.getName()).log(Level.SEVERE, null, ex);
										}
     }//GEN-LAST:event_jButton1ActionPerformed

					/**
					 * @param args the command line arguments
					 */
					public static void main(String args[]) {
										/* Set the Nimbus look and feel */
										//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
										/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
										 */
										try {
															for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
																				if ("Nimbus".equals(info.getName())) {
																									javax.swing.UIManager.setLookAndFeel(info.getClassName());
																									break;
																				}
															}
										} catch (ClassNotFoundException ex) {
															java.util.logging.Logger.getLogger(SQLTaulut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
										} catch (InstantiationException ex) {
															java.util.logging.Logger.getLogger(SQLTaulut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
										} catch (IllegalAccessException ex) {
															java.util.logging.Logger.getLogger(SQLTaulut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
										} catch (javax.swing.UnsupportedLookAndFeelException ex) {
															java.util.logging.Logger.getLogger(SQLTaulut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
										}
										//</editor-fold>

										/* Create and display the form */
										java.awt.EventQueue.invokeLater(new Runnable() {
															public void run() {
																				try {
																									new SQLTaulut().setVisible(true);
																				} catch (SQLException ex) {
																									Logger.getLogger(SQLTaulut.class.getName()).log(Level.SEVERE, null, ex);
																				} catch (ClassNotFoundException ex) {
																									Logger.getLogger(SQLTaulut.class.getName()).log(Level.SEVERE, null, ex);
																				}
															}
										});
					}

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JTable TilastotTable;
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JScrollPane jScrollPane2;
     // End of variables declaration//GEN-END:variables

					private void HaeTiedot() throws SQLException, ClassNotFoundException {
										DefaultTableModel model = (DefaultTableModel)TilastotTable.getModel();
										  int rowCount = model.getRowCount();
        
        for (int i = rowCount - 1; i >= 0; i--) {//Poistaa rivejä myyjät tablesta
        model.removeRow(i);
           
        }
        
										
										
											ArrayList<PTuote>p = new ArrayList();
	PTuote ti = new PTuote(0, "", 0.0, 0, 0.0);
						
        Connection con = JD.getConnection();
	String SA = "select * from ";			
        Statement stm = con.createStatement();
        ResultSet rs = stm.executeQuery(SA+"PTuote");
	Object t[] = new Object[20];	
StringBuilder sp = new StringBuilder();
        while(rs.next()){
				
				 				
        ti = new PTuote(0, rs.getString("nimi"), rs.getDouble("hinta"), rs.getInt("maara"), rs.getDouble("myyntihinta"));	
                                                                        
                                                                        System.out.println(sp);
													
									
													
													
	p.add(ti);
	} 
	DefaultTableModel m = (DefaultTableModel)TilastotTable.getModel();
	for (int i = 0; i < p.size(); i++) {
	t[0]=p.get(i).getNimi();
  t[1]=p.get(i).getHinta();
	t[2]=p.get(i).getMaara();
	t[3]=p.get(i).getMyyntiHinta();
	
        
	m.addRow(t);
	}
	con.close();
        
					
}
					}

